---
title: "References"
author: "Adam Chan, Khanh Chu, Shiyun Chen, Yuanling Zhu, Jing Jing He"
date: "`r format(Sys.time(), '%Y-%m-%d at %H:%M:%S')`"
output: 
    bookdown::html_document2:
        toc: true
        toc_float: 
            collapsed: false
        number_sections: true
        code_folding: show
        theme: united
        highlight: kate
        fig_caption: yes
        encoding: UTF-8
editor_options: 
  chunk_output_type: console
---

```{r setup_section_4, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reactable)
```

Agier, I., & Szafarz, A. (2013). Microfinance and gender: Is there a glass ceiling on loan size?. World development, 42, 165-181.   https://doi.org/10.1016/j.worlddev.2012.06.016

Belleflamme, P., Lambert, T., & Schwienbacher, A. (2014). Crowdfunding: Tapping the right crowd. Journal of Business Venturing, 29, 585-609. https://doi.org/10.1016/j.jbusvent.2013.07.003

Bouncken, R. B., Komorek, M., & Kraus, S. (2015). Crowdfunding: The current state of research. International Business & Economics Research Journal, 14, 407. https://doi.org/10.19030/iber.v14i3.9206

Cumming, D., Meoli, M., & Vismara, S. (2019). Investors’ choices between cash and voting rights: Evidence from dual-class equity crowdfunding. Research Policy, 48(8), 103740. https://doi.org/10.1016/j.respol.2019.01.014

Dorfleitner, G., Oswald, E. M., & Zhang, R. (2021). From credit risk to social impact: On the funding determinants in interest-free peer-to-peer lending. Journal of Business Ethics, 170, 375-400. https://doi.org/10.1007/s10551-019-04311-8 

Park, B., Genevsky, A., Knutson, B., & Tsai, J. (2020). Culturally valued facial expressions enhance loan request success. Emotion, 20(7), 1137–1153. https://doi.org/10.1037/emo0000642

Paruthi, G., Frias-Martinez, E., & Frias-Martinez, V. (2016). The role of rating and loan characteristics in online microfunding behaviors. Data For Good Exchange.  https://doi.org/10.48550/arXiv.1609.09571

Pengnate, S. F., & Riggins, F. J. (2020). The role of emotion in P2P microfinance funding: A sentiment analysis approach. International Journal of Information Management, 54, 102138. https://doi.org/10.1016/j.ijinfomgt.2020.102138 
