---
title: "Discussion"
author: "Adam Chan, Khanh Chu, Shiyun Chen, Yuanling Zhu, Jing Jing He"
date: "`r format(Sys.time(), '%Y-%m-%d at %H:%M:%S')`"
output: 
    bookdown::html_document2:
        toc: true
        toc_float: 
            collapsed: false
        number_sections: true
        code_folding: show
        theme: united
        highlight: kate
        fig_caption: yes
        encoding: UTF-8
editor_options: 
  chunk_output_type: console
---

```{r setup section_3, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
library(tidyverse)
library(NbClust)
library(GGally)
library(ggdendro)
library(purrr)
library(reactable)
```


## Dataset limitations and research direction shift

Our initial research question was aimed at identifying key predictive features of Kiva programs that achieve fundraising goals to develop models that predict future program success. However, upon more in-depth analysis of the dataset, we identified significant limitations that impacted our ability to effectively achieve this goal. The dataset we used was extracted through the Kiva API on May 15th, representing only a snapshot of ongoing projects at that time. It contains only a very limited number of programs (15 out of 6,493) that have reached funding status. Our ability to analyze completed projects (especially those that expired before the data extraction date) is severely limited because projects that have reached or exceeded their planned expiration date are no longer retrievable through the Kiva API. As a result, this snapshot limitation inherently biases the dataset toward active but incomplete funding status, preventing a balanced analysis of successful and unsuccessful funding completions.

Given the above limitations, it becomes impractical to construct predictive models using existing data. A lack of data on completed projects in the dataset will result in models that are less predictive and likely to be biased. Therefore, we shifted our research approach to cluster analysis. The new objective focuses on identifying different clusters or groups within projects based on their characteristics. Cluster analysis does not require a balanced dataset of outcome variables (e.g., funded vs. unfunded) and the primary goal is to discover patterns and relationships in the data. By grouping programs into clusters based on common characteristics, we aim to gain insight into the dynamics and key factors that influence Kiva's fundraising process. Once a more comprehensive and balanced dataset is available, these insights will greatly benefit future research efforts aimed at making predictions.

## Insights from cluster analysis

Our analysis identified five distinct clusters, each representing a unique profile of Kiva based on factors such as sentiment in project descriptions, loan amounts, repayment terms, and notably, the research score which indicates a project's alignment with Kiva's social impact goals.

Preliminary observations suggest that projects with higher internal research scores are likely to be funded more quickly and receive larger amounts. This finding aligns with Paruthi et al. (2016), which noted that higher ratings lead to increased loan activity, suggesting that lenders are more willing to invest in loans managed by highly rated field partners. This correlation raises a critical question about the criteria lenders use to select projects and the impact of Kiva ratings on these choices

Projects in **Cluster 1** exhibit higher sentiment scores and lower loan amounts, as well as relatively high research scores. Surprisingly, despite these positive metrics, they have longer funding cycles. Previous research, such as Pengnate & Riggins (2020), has found that the readability and emotional tone of loan descriptions significantly enhance the success rate of funding. Additionally, Park et al. (2020) noted that lenders from cultures that value excitement, such as the USA and Canada, tend to provide loans to borrowers who display high-arousal emotions. Our findings slightly diverge from previous research, suggesting that projects with emotional appeal but smaller financial needs may be more challenging to fund than expected. One possible explanation is that while this cluster exhibits more positive emotional displays in terms of description, their lower financial requirements might reflect less urgency or smaller impact, which in turn lengthens the loan period.

**Cluster 2** represents projects that can be considered "prestige projects," characterized by very high percentage of loan funded and high loan amounts. This cluster serves as a model for understanding the factors that contribute to rapid funding success. Additionally, projects within this cluster often have high research scores, indicating they are considered to have a significant social impact. This aligns with Dorfleitner et al. (2021), who emphasized the importance of third-party endorsements in establishing trust and enhancing funding success rates. Interestingly, projects led by men dominate this cluster, which resonates with the findings of Agier and Szafarz (2013). They highlighted potential gender disparities in loan conditions, especially in terms of loan sizes, with women receiving fewer loans than men when the project scales up. This trend prompts further exploration into potential gender biases within financing practices.

**Clusters 3 and 5** reflect different characteristics, generally showing moderate to good outcomes, with projects typically related to recreational or livelihood and needs improvements. These clusters include projects from various countries, notably including a significant portion from the Philippines, Senegal, Tajikistan, and Kyrgyzstan. These projects often fall within these two clusters, aligning with broader trends identified in previous research. According to Paruthi et al. (2016), specific loan characteristics, such as industry and country, significantly influence lending behaviors. This is evident in our cluster analysis, which highlights distinct preferences within certain industries and countries among these clusters. Park et al. (2020) also noted that cultural differences significantly impact lending preferences, which may explain the varied financing behaviors observed in these clusters. This insight is crucial for understanding how projects are perceived and supported differently across various cultural contexts.

**Cluster 4** is characterized by the longest funding period and notably lower research scores. Projects within this cluster demonstrate difficulty in attracting funds, and are arguably even the most likely to fail, which may be related to their lower impact rating. It is worth to mention, in the context of a gender ratio - 80% of projects are from women across the entire platform, the fact that half of the projects in this cluster are led by men is particularly prominent. This observation raises a pertinent question worth exploring: whether men, compared to women, face greater challenges in attracting funds when associated with lower research scores. This disparity suggests potential gender biases that might affect funding patterns, especially under conditions where the perceived impact or quality of the project is low.

To conclude our analysis of the clustering results, it is evident that Kiva projects display a significant heterogeneity in their characteristics, which underscores the complex nature of crowdfunding dynamics in microfinance. Such variability demands that predictive models or prescriptive strategies be finely tailored to recognize and enhance the unique aspects of each cluster to optimize funding success and social impact effectively.

Furthermore, we acknowledged the clusters are temporal-sensitive as they are subjected to the time that we scrape Kiva using API. Nevertheless, we defined these clusters in grounded characteristics, allowing new projects to be categorized into one of the five existing labels. We anticipate that while the composition of these clusters (in terms of size and spatial distribution) may vary over time, their fundamental labels will remain consistent. Thus, continuous monitoring and periodic recalibration of clustering models are crucial to maintain their relevance and accuracy in predicting and enhancing the success of Kiva projects.

## Recommendations for research and business

The differences among the clusters, particularly regarding the funding periods and loan amounts, provide valuable lessons for future predictive modeling. Additionally, the role of research scores as predictors of funding speed is particularly noteworthy. Projects with higher scores tend to attract funding more quickly, indicating that donors are influenced by Kiva's assessment of potential social impact. This finding emphasizes the importance of accurately assessing and communicating the anticipated impact of projects to potential donors.

Investigate the impact of gender on funding outcomes in more depth, as observed in the unique patterns within Clusters 2 and 4, is also crucial. Research should focus on whether there are systemic biases against a particular gender within the funding process.

Further studies are needed to understand how cultural differences affect lending behaviors and preferences, as demonstrated by the distinct outcomes in different clusters, especially Clusters 3 and 5. This can help refine Kiva's approach to better align with cultural expectations and practices in different regions. These insights not only enhance the predictive capabilities for future models but also contribute to more equitable and effective funding strategies.

## Limitation

Primarily, our analysis is based on a single snapshot of the platform, which might not fully capture the dynamic nature of project compositions that can change significantly over time. Ideally, multiple snapshots throughout the year would provide a more robust understanding of trends and allow us to observe shifts in project characteristics and lender behaviors.

Furthermore, our interpretation of the data is inherently limited by our current understanding and perspective. We present findings based on observable data; however, different analysts might draw distinct conclusions from the same information. This subjective nature of data interpretation suggests that there may be additional insights and connections that remain undiscovered, particularly due to the constraints of time and scope in our analysis.

A significant limitation of our current stage is the inability to perform predictive modeling. Future research should focus on expanding the dataset to include more comprehensive attributes of projects that were either successfully funded or failed despite meeting funding deadlines. This expanded dataset would allow for a deeper exploration of predictive factors and contribute to more effective modeling.

Moreover, as more comprehensive data become available, further research could explore the application of advanced machine-learning techniques for both clustering and predictive modeling. Such techniques would likely enhance the accuracy and utility of the models, providing Kiva with better tools to assess and promote projects effectively. Embracing more sophisticated analytics will enable us to refine our predictions and strategies, ultimately improving Kiva's capacity to foster positive social and economic outcomes through its projects.