---
title: "Written Report - Analyzing Digital Footprint - Group 6"
author: "Adam Chan, Khanh Chu, Shiyun Chen, Yuanling Zhu, Jing Jing He"
date: "`r format(Sys.time(), '%Y-%m-%d at %H:%M:%S')`"
output: 
    bookdown::html_document2:
        toc: true
        toc_float: 
            collapsed: false
        number_sections: true
        code_folding: show
        theme: united
        highlight: kate
        fig_caption: yes
        encoding: UTF-8
        css: !expr here::here("style.css")
editor_options: 
  chunk_output_type: console
---

```{r setup main_report, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
library(tidyverse)
library(NbClust)
library(GGally)
library(ggdendro)
library(purrr)
library(stargazer)
library(reactable)
```

# Introduction

```{r, child=here::here("sections","section_1", "section_1_main.Rmd")}
```

# Data

```{r, child=here::here("sections","section_2", "section_2_main.Rmd")}
```

# Discussion

```{r, child=here::here("sections","section_3", "section_3_main.Rmd")}
```

# References

```{r, child=here::here("sections","section_4", "section_4_main.Rmd")}
```



